CREATE TABLE Framework(Framework_ID TEXT NOT NULL,Name TEXT,CPU INTEGER,Memory REAL,Active INTEGER DEFAULT FALSE NOT NULL,Scheduled_Tasks INTEGER DEFAULT FALSE,TimeStamp TIMESTAMP NOT NULL);
CREATE UNIQUE INDEX Framework_Framework_ID_uindex ON Framework (Framework_ID);
CREATE TABLE Slave(Slave_ID TEXT NOT NULL,Load_5min REAL,Free_Memory REAL,Total_Memory REAL,CPU INTEGER,Allocated_CPU REAL,IP TEXT NOT NULL,Hostname TEXT,TimeStamp TIMESTAMP NOT NULL);
CREATE UNIQUE INDEX Slave_Slave_ID_uindex ON Slave (Slave_ID);
CREATE TABLE Runs_On(Framework_ID TEXT,Slave_ID TEXT,FOREIGN KEY (Slave_ID) REFERENCES Slave (Slave_ID) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY (Framework_ID) REFERENCES Framework (Framework_ID) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED);
